---
# tasks file for roles/pushgateway

- name: Installation du Pushgateway
  become: yes
  unarchive:
    src: "{{ pushgateway_download_url }}"
    dest: "/tmp"
    remote_src: true
  tags:
    - install

- name: Démarrage du service Pushgateway
  become: yes
  systemd:
    name: pushgateway.service
    enabled: yes
    state: started
  tags:
    - start_service
