version: '3'
services:
        postgres:
                build: postgres/
                container_name: ${PG_CONTAINER_NAME}
                environment:
                        POSTGRES_DB: ${POSTGRES_DB}
                        POSTGRES_USER: ${POSTGRES_USER}
                        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
                        PGDATA: ${PGDATA}
                volumes:
                        - postgres:/var/lib/pgsql
                ports:
                        - ${PG_PORT}
                restart: unless-stopped
        pgadmin4:
               build: pgadmin4/
               container_name: ${PGADMIN_CONTAINER_NAME}
               environment:
                       PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
                       PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
               ports:
                       - ${PGADMIN_PORT}
               restart: unless-stopped
        grafana:
                image: grafana/grafana:latest
                ports:
                        - "3000:3000"
                environment:
                        - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
                volumes:
                        - grafana_data:/var/lib/grafana

        pushgateway:
                image: prom/pushgateway:latest
                ports:
                        - "9090:9090"
                command: ["--web.listen-address=:9090"]

        node_exporter:
                image: prom/node-exporter:latest
                ports:
                        - "9100:9100"
                command: ["--collector.textfile.directory=/etc/node-exporter/textfile_collector"]
                volumes:
                        - ./node-exporter:/etc/node-exporter/textfile_collector
volumes:
        postgres:
                driver: local
                driver_opts:
                        type: 'none'
                        o: 'bind'
                        device: /data/

        grafana_data:
